# -*- coding: utf-8 -*-
"""Final_Project_DEMO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FntshnU0FFa0LPPwGNpftY9O_Qw6rVN5

# 🌿 Plant Disease Detection: Live Demo
**Project:** Foundational AI Course

**Student:** Tadiwos Andargie and Daniel Manga

This notebook demonstrates the real-time performance of the trained MobileNetV2 model.
We will load the saved model and test it on new images downloaded from the internet.
"""

#prepare tensorflow

!pip install tensorflow
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.utils import load_img, img_to_array

#upload model
from google.colab import files
files.upload()
#plant_disease_model_60_20_20.keras

#load
model = tf.keras.models.load_model('plant_disease_model_60_20_20.keras')
print("Model loaded successfully!")

"""### 🔍 Predict a New Image
Run the cell below to upload a plant leaf image. The model will analyze it and predict the disease class with a confidence score.
"""

#class names
#copy list from the main notebook
class_names = ['Apple___Apple_scab', 'Apple___Black_rot', 'Apple___Cedar_apple_rust',
               'Apple___healthy', 'Blueberry___healthy', 'Cherry_(including_sour)___Powdery_mildew',
               'Cherry_(including_sour)___healthy', 'Corn_(maize)___Cercospora_leaf_spot_Gray_leaf_spot',
               'Corn_(maize)___Common_rust_', 'Corn_(maize)___Northern_Leaf_Blight', 'Corn_(maize)___healthy',
               'Grape___Black_rot', 'Grape___Esca_(Black_Measles)', 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)',
               'Grape___healthy', 'Orange___Haunglongbing_(Citrus_greening)', 'Peach___Bacterial_spot',
               'Peach___healthy', 'Pepper,_bell___Bacterial_spot', 'Pepper,_bell___healthy',
               'Potato___Early_blight', 'Potato___Late_blight', 'Potato___healthy',
               'Raspberry___healthy', 'Soybean___healthy', 'Squash___Powdery_mildew',
               'Strawberry___Leaf_scorch', 'Strawberry___healthy', 'Tomato___Bacterial_spot',
               'Tomato___Early_blight', 'Tomato___Late_blight', 'Tomato___Leaf_Mold',
               'Tomato___Septoria_leaf_spot', 'Tomato___Spider_mites_Two-spotted_spider_mite',
               'Tomato___Target_Spot', 'Tomato___Tomato_Yellow_Leaf_Curl_Virus', 'Tomato___Tomato_mosaic_virus',
               'Tomato___healthy']

#predict function
def predict_image(image_path, model):
  img = load_img(image_path, target_size=(224, 224))
  img_array = img_to_array(img)
  img_batch = np.expand_dims(img_array, axis=0)

  prediction = model.predict(img_batch)

  predicted_class = class_names[np.argmax(prediction[0])]
  confidence = np.max(prediction[0]) * 100

  plt.imshow(img)
  plt.title(f"{predicted_class} ({confidence:.2f}%)")
  plt.axis("off")

#upload a test image
from google.colab import files
uploaded = files.upload()

#filename of the uploaded image
filename = list(uploaded.keys())[0]

# Run prediction!
predict_image(filename, model)